### ISSUE TITLE
Using  modern ui style for windows controls

### ISSUE THREAD

**Issue by funbiscuit** [samhocevar/portable-file-dialogs#22]
Current version of pfd uses MessageBox to create dialogs and they look ugly with win98 styled buttons. That's comparison of how messagebox looks on windows xp with new (top) and old (bottom) style:
![image](https://user-images.githubusercontent.com/9351181/64014239-56647580-cb2a-11e9-8e1e-8d84eeeb8f3f.png)

File open dialog is also looks better on XP with new style than the old style:
![image](https://user-images.githubusercontent.com/9351181/64014266-64b29180-cb2a-11e9-8623-939b57c55c9a.png)
![image](https://user-images.githubusercontent.com/9351181/64014270-68deaf00-cb2a-11e9-9657-04adc85f84b4.png)

And on windows 7:
![image](https://user-images.githubusercontent.com/9351181/64014319-80b63300-cb2a-11e9-9d31-08c27f939987.png)

New look can be added either by creatin manifes file (then this will be no longer single-header so that's not appropriate). Or with Visual Studio 2005 and higher by using the following pragma:

```
#pragma comment(linker,"\"/manifestdependency:type='win32' \
name='Microsoft.Windows.Common-Controls' version='6.0.0.0' \
processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
```

I don't actually know if this pragma will not conflict with any user project manifest. I think that combining this pragma with some define check would be the best. So user can disable new style if it's really needed:

```
// use this define to disable manifest dependency
//#define _PFD_DISABLE_MANIFEST 1

#if _MSC_VER && !_PFD_DISABLE_MANIFEST
#pragma comment(linker,"\"/manifestdependency:type='win32' \
name='Microsoft.Windows.Common-Controls' version='6.0.0.0' \
processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
#endif
```

If this behavior is appropriate I can do a pull request. If not, what would you suggest? Maybe even invert behavior and let user to specifically tell library to apply new look instead of doing it by default. But I would suggest appply it by default.

**Comment by samhocevar** [comment]
Right now I like the `#pragma` and the macro to optionally disable it.

It would be great if, again, there was a way to do this at runtime instead of modifying the way the user build their software. I do not have a solution yet but I’m leaving some information for future reference:
  * [How can you use both versions 5 and 6 of the common controls within the same module?
](https://devblogs.microsoft.com/oldnewthing/?p=1043)
  * [How to enable visual styles without a manifest](https://stackoverflow.com/q/4308503/111461)
  * [How to enable 'Microsoft.Windows.Common-Controls' for specificate control?](https://stackoverflow.com/q/51969459/111461)

I have quickly tried the above solutions with `pfd::message` (VS2017, Windows 10) and none of them seemed to work ☹

**Comment by samhocevar** [comment]
Thanks, your work in #24 was successfully merged!
