### ISSUE TITLE
Message windows dont appear in focus.

### ISSUE THREAD

**Issue by DomRe** [samhocevar/portable-file-dialogs#52]
When a messagebox is created it seems that the box is created behind other active applications. It should be set so its the current focus.

**Comment by samhocevar** [comment]
On what platform do you observe this? Also, does the application have focus at the moment the messagebox is created?

**Comment by DomRe** [comment]
Windows, and yes.

**Comment by samhocevar** [comment]
I was unable to reproduce it exactly, but I got somewhat of a repro with a test program that does not create a window at all. It appears that replacing `MB_TOPMOST` with `MB_SYSTEMMODAL` in `message::message()` fixes it for me, can you please confirm?

I am however confused by [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox) because according to it `MB_TOPMOST` should work as expected:
 - _**MB_APPLMODAL** is the default_
 - _**MB_TOPMOST**: The message box is created with the **WS_EX_TOPMOST** window style_
 - _**MB_SYSTEMMODAL**: Same as **MB_APPLMODAL** except that the message box has the **WS_EX_TOPMOST** style_

It could be because your main window stops pumping messages while the message box is displayed (which should not be a problem at all, just something I overlooked). Does your application continue to run while the dialog is displayed or does it just wait for user input?

**Comment by DomRe** [comment]
Can confirm that replacing ```MB_TOPMOST``` with ```MB_SYSTEMMODAL``` fixed the issue.
